[package]
name = "pap-config"
version = "0.1.0"
edition = "2021"
license.workspace = true
readme.workspace = true

[dependencies]
schemars = "1.0.0-alpha.15"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9.34"
